/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"

int main(void)
{
	GPIOx_Handler_t gpio;
	gpio.pGPIOx = GPIOA;

	GPIO_PCLK_Ctrl(gpio.pGPIOx, EN);

	GPIO_PinConfig_t* temp = &(gpio.GPIO_PinConfig);
	temp->GPIO_PinNo = GPIO_P1;
	temp->GPIO_PinMode = GPIO_OUT;
	temp->GPIO_PinModeOType = GPIO_OD;
	temp->GPIO_PinOSpeed = GPIO_VHIGH;
	temp->GPIO_PinPUPD = GPIO_PD;

	GPIO_Init(&gpio);
	for(;;);
}
